package com.example.entity.enums;

public enum Course {
    COMPUTER_SCIENCE,
    PROGRAMMING,
    DATA_SCIENCE,
    ARTIFICIAL_INTELLIGENCE,
    CYBER_SECURITY,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    SOFTWARE_ENGINEERING,
    NETWORKING,
    CLOUD_COMPUTING
}
